repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        name: Ruff lint
        stages: [pre-commit]
        args: [--fix]  # This will automatically fix linting issues

      - id: ruff
        name: Ruff format
        stages: [pre-commit]
        args: [--fix]  # For fixing only formatting issues