name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use your desired Python version

    # Install Ruff
    - name: Install Ruff
      run: pip install ruff

    # Run Ruff for lint checking
    - name: Run Ruff
      run: ruff check .
